version: "3"

services:
  mongodb:
    image: mongo:latest
    tty: true
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - '${MONGO_PORT}:27017'
    command: mongod --smallfiles # --logpath=/dev/null # --quiet

  jogging-api:
    build: .
    tty: true
    volumes:
      - .:/usr/app
    env_file:
      - .env
    ports:
      - '${API_PORT}:${API_PORT}'