version: "3"

services:
  mongodb:
    image: mongo:latest
    tty: true
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27018
    command: mongod --smallfiles # --logpath=/dev/null # --quiet

  jogging-api:
    build: .
    tty: true
    volumes:
      - .:/usr/app
    environment:
      - NODE_ENV=development
    ports:
      - '4040:4040'